#!/usr/bin/env node
/**
 * setup.js — JamRoom environment configurator
 *
 * Usage:
 *   npm run setup dev     →  local dev (backend on localhost:4000, Vite proxy)
 *   npm run setup prod    →  production (Render backend, Netlify frontend)
 *
 * What it does:
 *   - Writes web/.env  (VITE_SERVER_URL for the frontend)
 *   - Writes .env      (server vars, only updates VITE_SERVER_URL + NODE_ENV)
 *   - Prints a summary of the configured environment
 */

const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const ROOT_ENV = path.join(ROOT, '.env');
const WEB_ENV = path.join(ROOT, 'web', '.env');

/* ── Environment profiles ── */
const profiles = {
    dev: {
        NODE_ENV: 'development',
        VITE_SERVER_URL: '',                        // blank → Vite proxy to localhost:4000
        description: 'Local development (backend on localhost:4000)'
    },
    prod: {
        NODE_ENV: 'production',
        VITE_SERVER_URL: 'https://jamroon-y3c0.onrender.com',
        description: 'Production (Render backend + Netlify frontend)'
    }
};

/* ── Parse args ── */
const arg = process.argv[2]?.toLowerCase();

if (!arg || !profiles[arg]) {
    console.log(`
╔═══════════════════════════════════════╗
║   JamRoom Environment Setup           ║
╚═══════════════════════════════════════╝

Usage:  npm run setup <env>

  dev   — ${profiles.dev.description}
  prod  — ${profiles.prod.description}

Example:
  npm run setup dev
  npm run setup prod
`);
    process.exit(arg ? 1 : 0);
}

const profile = profiles[arg];

/* ── Helper: read existing .env as key=value map ── */
function readEnv(filePath) {
    const map = new Map();
    if (!fs.existsSync(filePath)) return map;
    const lines = fs.readFileSync(filePath, 'utf8').split('\n');
    for (const line of lines) {
        const trimmed = line.trim();
        if (!trimmed || trimmed.startsWith('#')) continue;
        const eqIdx = trimmed.indexOf('=');
        if (eqIdx === -1) continue;
        const key = trimmed.slice(0, eqIdx).trim();
        const val = trimmed.slice(eqIdx + 1).trim();
        map.set(key, val);
    }
    return map;
}

/* ── Helper: write .env from map ── */
function writeEnv(filePath, map, header = '') {
    let content = header ? `# ${header}\n` : '';
    for (const [k, v] of map) {
        content += `${k}=${v}\n`;
    }
    fs.writeFileSync(filePath, content, 'utf8');
}

/* ── Update root .env (preserve existing keys like SOUNDCLOUD_*) ── */
const rootMap = readEnv(ROOT_ENV);
rootMap.set('NODE_ENV', profile.NODE_ENV);
rootMap.set('VITE_SERVER_URL', profile.VITE_SERVER_URL);
// Ensure defaults exist
if (!rootMap.has('PORT')) rootMap.set('PORT', '4000');
writeEnv(ROOT_ENV, rootMap, `JamRoom — ${arg} environment`);

/* ── Write web/.env (only VITE_ vars matter for Vite) ── */
const webMap = new Map();
webMap.set('VITE_SERVER_URL', profile.VITE_SERVER_URL);
writeEnv(WEB_ENV, webMap, `JamRoom web — ${arg} (auto-generated by setup.js)`);

/* ── Summary ── */
console.log(`
╔═══════════════════════════════════════╗
║   ✅  Environment: ${arg.toUpperCase().padEnd(18)}    ║
╚═══════════════════════════════════════╝

  ${profile.description}

  📄  ${path.relative(ROOT, ROOT_ENV)}
      NODE_ENV          = ${profile.NODE_ENV}
      VITE_SERVER_URL   = ${profile.VITE_SERVER_URL || '(empty — uses Vite proxy)'}

  📄  ${path.relative(ROOT, WEB_ENV)}
      VITE_SERVER_URL   = ${profile.VITE_SERVER_URL || '(empty — uses Vite proxy)'}

  Next steps:
${arg === 'dev' ? `    npm run dev        — start both server + frontend
    npm run dev:server — start backend only (port 4000)
    npm run dev:web    — start frontend only (port 5173)` : `    npm run deploy     — build + deploy to Netlify`}
`);
